#!/bin/bash

# Gracefully reload Gunicorn by sending the HUP signal to the master process
# This will cause Gunicorn to reload its configuration and restart the workers

pgrep gunicorn | xargs kill -HUP
